MODEL:
  TYPE: MaxViT
  NAME: max_vit_tiny_224
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 1
  MAX_VIT:
    EMBED_DIM: 64
    DEPTHS: [2, 2, 5, 2]
    DIM_HEAD: 32
    WINDOW_SIZE: [7, 7]
    POOL: "avg"
    CHANNELS: (64, 128, 256, 512)
